day eleven, pt 1 (cont)

diff --git a/day_eleven/pt1_solution b/day_eleven/pt1_solution
--- a/day_eleven/pt1_solution
+++ b/day_eleven/pt1_solution
@@ -7,14 +7,21 @@
   print "Error: \'input\' not found"
 }
 
+# include zsh_libmisc, load needed library functions
+fpath=(/usr/lib/zsh_libmisc/libmisc.zwc $fpath)
+autoload query_jobs
+
+# load zsh/zselect for tiny-increment sleep
+zmodload zsh/zselect
+
 # alias integer to int for brevity
 alias int="integer"
 
 # array declarations
-declare -a dayeleven_input outboxes machines worker_ids
+declare -a dayeleven_input outboxes machines
 
 # variable declarations
-int worker_id result
+int result z_jobs outbox_res you_res
 
 # read input into linear array
 dayeleven_input=("${(@f)$(<input)}")
@@ -45,6 +52,47 @@ is_outbox() {
 
 # recursive create_worker function
 create_worker() {
+  # fetch working machine
+  working="$1"
+  # randomize worker id rather than increment since we're recursing
+  # this algorithm doesn't care about order anyways, at least in theory
+  worker_id="$RANDOM"
+  until ! [ -f /tmp/dayeleven_working/"$worker_id".claim ]; do
+    worker_id="$RANDOM"
+  done
+  touch /tmp/dayeleven_working/"$worker_id".claim
+  ## 1 - outbox / you handling
+  # if machine is outbox, we've completed a path.
+  is_outbox "$working" && {
+    touch /tmp/dayeleven_working/"$worker_id".outbox
+    return 0
+  }
+  # if machine is you, we must end here or we'll infinitely loop.
+  # instead, increment "you counter" to determine multiplication result
+  [ "$working" = 'you' ] && {
+    touch /tmp/dayeleven_working/"$worker_id".you
+    # don't stop here if this is our first loop through
+    ! [ -f /tmp/dayeleven_working/firstloop ] && {
+      rm -rf /tmp/dayeleven_working/firstloop
+    } || {
+      return 0
+    }
+  }
+  ## 2 - begin recursion (if we've reached here, we're not outbox nor you)
+  # fetch links via nested variable print
+  working_links=$(eval print $"$working")
+  # continue recursion for every link
+  IFS=$' '
+  for i in $=working_links; do
+    [ "$(query_jobs)" -ge "$j" ] && {
+      until ! [ "$(query_jobs)" -ge "$j" ]; do
+        zselect -t 5
+      done
+    }
+    create_worker "$i"
+  done
+  unset IFS
+  return 0
 }
 
 ## parsing steps
@@ -65,7 +113,7 @@ for line in $dayeleven_input; do
   ## 3 - create machine links
   IFS=$' '
   for link in $=line; do
-    eval $machine_name+=" $link"
+    eval "$machine_name"+=" $link"
   done
   unset IFS
 done
@@ -73,3 +121,32 @@ done
 
 ## main
 
+# start create_worker recursion
+touch /tmp/dayeleven_working/firstloop
+create_worker you
+
+# until all workers complete, do nothing
+z_jobs=$(query_jobs)
+until ((z_jobs == 0)); do
+  zselect -t 5
+  z_jobs=$(query_jobs)
+done
+
+# tally outboxes
+for i in /tmp/dayeleven_working/*.outbox; do
+  ((outbox_res++))
+done
+
+# tally you repetitions
+for i in /tmp/dayeleven_working/*.you; do
+  ((you_res++))
+done
+
+# multiply you by outbox to get final result
+((result=(outbox_res*you_res)))
+
+# print results
+print $result
+
+# cleanup
+rm -rf /tmp/dayeleven_working
